=== adnasa/sphere-sunrise-design/input/templates/schema/page.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {

    "newsLetterWidget": {
      "type": "object",
      "properties": {
        "text" :  {"type": "string"},
        "textAlt" : {"type": "string"},
        "url" : {"type": "string"},
        "placeholderText" : {"type": "string"}
      }
    },

    "accessWidget": {
      "type": "object",
      "properties": {
        "loggedIn": {"type": "boolean"},
        "signIn": {"$ref": "common.json#/definitions/link"},
        "signUp": {"$ref": "common.json#/definitions/link"}
      }
    },

    "cartWidget": {
      "type": "object",
      "properties": {
        "cartLink": {"$ref": "common.json#/definitions/link"},
        "numItems": {"type": "integer"}
      }
    },

    "localizationWidget": {
      "languages": {
        "type": "array",
        "items": {"$ref": "common.json#/definitions/selectable"}
      },
      "countries": {
        "type": "array",
        "items": {"$ref": "common.json#/definitions/selectable"}
      }
    },

    "navigation": {
      "type": "object",
      "properties": {
        "newLink": {"$ref": "common.json#/definitions/link"},
        "saleLink": {"$ref": "common.json#/definitions/link"},
        "categories": {"$ref": "common.json#/definitions/link-tree"},
        "brands": {"$ref": "common.json#/definitions/link-tree"}
      }
    },

    "header": {
      "type": "object",
      "properties": {
        "title": {"type": "string"},
        "storesLink": {"$ref": "common.json#/definitions/link"},
        "helpLink": {"$ref": "common.json#/definitions/link"},
        "contactLink": {"$ref": "common.json#/definitions/link"},
        "localizationWidget": {"$ref": "#/definitions/localizationWidget"},
        "accessWidget": {"$ref": "#/definitions/accessWidget"},
        "cartWidget": {"$ref": "#/definitions/cartWidget"},
        "navigation": {"$ref": "#/definitions/navigation"},
        "seo": {"$ref": "common.json#/definitions/detail"}
      }
    },

    "footer": {
      "type": "object",
      "properties": {
        "paySecureHeading": {"type": "string"},
        "followUsText": {"type": "string"},
        "newsletterWidget": {"$ref": "#/definitions/newsletterWidget"},
        "customerCareHeading": {"type": "string"},
        "customerCareLinks": {
          "type": "array",
          "items": {"$ref": "common.json#/definitions/link"},
          "minItems": 5,
          "uniqueItems": true
        },
        "aboutUsHeading": {"type": "string"},
        "aboutUsLinks": {
          "type": "array",
          "items": {"$ref": "common.json#/definitions/link"},
          "minItems": 2,
          "uniqueItems": true
        },
        "shortcutsHeading": {"type": "string"},
        "shortcutsLinks": {
          "type": "array",
          "items": {"$ref": "common.json#/definitions/link"},
          "minItems": 4,
          "uniqueItems": true
        },
        "legalInfoHeading": {"type": "string"},
        "legalInfoLinks": {
          "type": "array",
          "items": {"$ref": "common.json#/definitions/link"},
          "minItems": 3,
          "uniqueItems": true
        }
      }
    },

    "meta": {
      "type": "object",
      "properties": {
        "assetsPath": {"type": "string"}
      }
    }
  },

  "title": "page",
  "type": "object",
  "properties": {
    "header" : {"$ref": "#/definitions/header"},
    "footer": {"$ref": "#/definitions/footer"},
    "seo": {"$ref": "common.json#/definitions/detail"},
    "content": {
      "oneOf": [
        { "$ref": "pdp.json#/content" },
        { "$ref": "pop.json#/content" }
      ]
    },
    "meta": {"$ref": "#/definitions/meta"}
  }
}

=== adnasa/sphere-sunrise-design/input/templates/my-account-wishlist.json
{
	"header" : { "$ref" : "common/header.json" },
	"footer" : { "$ref" : "common/footer.json" },
	"content" : {
		"pageTitle" : "My Account",
		"sidebarItemOne" : {
			"text" : "Personal Details",
			"url" : ""
		},
		"sidebarItemTwo" : {
			"text" : "Address Book",
			"url" : ""
		},
		"sidebarItemThree" : {
			"text" : "Payment Details",
			"url" : ""
		},
		"sidebarItemFour" : {
			"text" : "My Orders",
			"url" : ""
		},
		"sidebarItemFive" : {
			"text" : "Returns / Exchange",
			"url" : ""
		},
		"sidebarItemSix" : {
			"text" : "Wishlist",
			"url" : "",
			"wishlistItems" : "12"
		},
		"sidebarItemSeven" : {
			"text" : "Sign Out",
			"url" : ""
		},
        "contentTitle" : "My Wishlist:",
		"itemsInTotal" : "3 items in total",
		"clearWishlistBtn" : "Clear Wishlist",
		"removeBtn" : "Remove",
        "pagination" : { "$ref" : "catalog/pagination.json" },
        "display" : {
            "title" : "Items per page",
            "list" : [
                {
                    "name" : "12",
                    "value" : "12",
                    "selected" : false
                },
                {
                    "name" : "24",
                    "value" : "24",
                    "selected" : true
                },
                {
                    "name" : "48",
                    "value" : "48",
                    "selected" : false
                }
            ]
        },
		"products" : { "$ref" : "catalog/product-list3.json" }
	},
    "meta" : { "$ref" : "common/meta.json" }
}

=== adnasa/sphere-sunrise-design/input/templates/checkout-signin.json
{
	"header" : {
		"title" : "Sunrise - Checkout Sign In Page",
		"customerService" : "Need help? Customer Service",
		"customerServiceNumber" : "+12 345 6000"
	},
	"footer" : {
		"legalInfo" : {
			"text" : "Â© 2015 Sunrise",
			"list" : [
				{
					"text" : "Imprint",
					"url" : ""
				},
				{
					"text" : "Privacy policy",
					"url" : ""
				},
				{
					"text" : "Terms of use",
					"url" : ""
				}
			]
		}
	},
  "content" : {
    "secureCheckoutTitle" : "Secure Checkout - Sign In"
  },
  "meta" : {
    "assetsPath": "assets/"
  }
}

=== adnasa/sphere-sunrise-design/input/templates/no-search-result.json
{
    "header" : { "$ref" : "common/header.json" },
    "footer" : { "$ref" : "common/footer.json" },
    "content" : {
        "breadcrumb" : { "$ref" : "catalog/breadcrumb.json" },
        "suggestions" : { "$ref" : "catalog/product-list4.json" }
    },
    "meta" : { "$ref" : "common/meta.json" }
}

=== adnasa/sphere-sunrise-design/input/templates/checkout-thankyou.json
{
	"header" : { "$ref" : "common/checkout-header.json" },
	"footer" : { "$ref" : "common/checkout-footer.json" },
  "content" : {
      "order" : { "$ref" : "checkout/cart.json" },
      "shippingAddress" : { "$ref" : "checkout/shipping-address.json" },
      "billingAddress" : { "$ref" : "checkout/billing-address.json" },
    "emailSentTo" : "An email has been sent to",
    "email" : "camilo@batman.com",
    "emailSentToEnding" : "as a copy of this confirmation purchase",
    "receiptBtn" : "Print Receipt",
    "continueShoppingBtn" : "Continue Shopping",
    "orderDetailsTitle" : "Your order details",
    "orderNumberTitle" : "Order Number",
    "orderNumber" : "01445678",
    "orderDateTitle" : "Order Date",
    "orderDate" : "Nov 14, 2015",
		"shippingMethod" : {
			"text" : "Shipping Method",
			"description" : "DHL Standard - Delivery 3-5 Days"
		},
		"paymentDetails" : {
			"text" : "Payment Details",
			"type" : "Credit Card",
			"name" : "Bruce Wayne",
			"card" : "Visa",
			"number" : "**** **** **** **56",
			"date" : "09.18"
		},
    "cartItems" : {
      "description" : "Product Description",
      "price" : "Price",
      "totalPrice" : "Total Price",
      "list" : [
        {
          "nameHeadline" : "Enditatem Product Name",
          "nameSubline" : "Optional Line Two",
          "sku" : "Sunrise #SUN123456",
          "color" : "Navy Blue",
          "size" : "M",
          "available" : "Available",
					"quantity" : "2",
          "price" : "49,00 €",
          "totalPrice" : "49,00 €"
        },
        {
          "nameHeadline" : "Enditatem Product Name",
          "nameSubline" : "Optional Line Two",
          "sku" : "Sunrise #SUN123456",
          "color" : "Navy Blue",
          "size" : "M",
          "available" : "Available",
          "quantity" : 3,
          "price" : "49,00 €",
          "totalPrice" : "49,00 €"
        }
      ]
    },
		"totalSum" : {
			"subtotal" : "107,00 €",
			"orderDiscountTitle" : "Order Discount",
			"orderDiscount" : "0,00 €",
			"deliveryOption" : "Standard Delivery",
			"delivery" : "0,00 €",
			"tax" : "20,00 €",
			"orderTotalTitle" : "Order Total",
			"orderTotal" : "117,00 €"
		}
  },
  "meta" : {
	"assetsPath": "assets/"
  }
}
