=== adnasa/sphere-sunrise-design/input/templates/schema/page.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {

    "newsLetterWidget": {
      "type": "object",
      "properties": {
        "text" :  {"type": "string"},
        "textAlt" : {"type": "string"},
        "url" : {"type": "string"},
        "placeholderText" : {"type": "string"}
      }
    },

    "accessWidget": {
      "type": "object",
      "properties": {
        "loggedIn": {"type": "boolean"},
        "signIn": {"$ref": "common.json#/definitions/link"},
        "signUp": {"$ref": "common.json#/definitions/link"}
      }
    },

    "cartWidget": {
      "type": "object",
      "properties": {
        "cartLink": {"$ref": "common.json#/definitions/link"},
        "numItems": {"type": "integer"}
      }
    },

    "localizationWidget": {
      "languages": {
        "type": "array",
        "items": {"$ref": "common.json#/definitions/selectable"}
      },
      "countries": {
        "type": "array",
        "items": {"$ref": "common.json#/definitions/selectable"}
      }
    },

    "navigation": {
      "type": "object",
      "properties": {
        "newLink": {"$ref": "common.json#/definitions/link"},
        "saleLink": {"$ref": "common.json#/definitions/link"},
        "categories": {"$ref": "common.json#/definitions/link-tree"},
        "brands": {"$ref": "common.json#/definitions/link-tree"}
      }
    },

    "header": {
      "type": "object",
      "properties": {
        "title": {"type": "string"},
        "storesLink": {"$ref": "common.json#/definitions/link"},
        "helpLink": {"$ref": "common.json#/definitions/link"},
        "contactLink": {"$ref": "common.json#/definitions/link"},
        "localizationWidget": {"$ref": "#/definitions/localizationWidget"},
        "accessWidget": {"$ref": "#/definitions/accessWidget"},
        "cartWidget": {"$ref": "#/definitions/cartWidget"},
        "navigation": {"$ref": "#/definitions/navigation"},
        "seo": {"$ref": "common.json#/definitions/detail"}
      }
    },

    "footer": {
      "type": "object",
      "properties": {
        "paySecureHeading": {"type": "string"},
        "followUsText": {"type": "string"},
        "newsletterWidget": {"$ref": "#/definitions/newsletterWidget"},
        "customerCareHeading": {"type": "string"},
        "customerCareLinks": {
          "type": "array",
          "items": {"$ref": "common.json#/definitions/link"},
          "minItems": 5,
          "uniqueItems": true
        },
        "aboutUsHeading": {"type": "string"},
        "aboutUsLinks": {
          "type": "array",
          "items": {"$ref": "common.json#/definitions/link"},
          "minItems": 2,
          "uniqueItems": true
        },
        "shortcutsHeading": {"type": "string"},
        "shortcutsLinks": {
          "type": "array",
          "items": {"$ref": "common.json#/definitions/link"},
          "minItems": 4,
          "uniqueItems": true
        },
        "legalInfoHeading": {"type": "string"},
        "legalInfoLinks": {
          "type": "array",
          "items": {"$ref": "common.json#/definitions/link"},
          "minItems": 3,
          "uniqueItems": true
        }
      }
    },

    "meta": {
      "type": "object",
      "properties": {
        "assetsPath": {"type": "string"}
      }
    }
  },

  "title": "page",
  "type": "object",
  "properties": {
    "header" : {"$ref": "#/definitions/header"},
    "footer": {"$ref": "#/definitions/footer"},
    "seo": {"$ref": "common.json#/definitions/detail"},
    "content": {
      "oneOf": [
        { "$ref": "pdp.json#/content" },
        { "$ref": "pop.json#/content" }
      ]
    },
    "meta": {"$ref": "#/definitions/meta"}
  }
}

=== adnasa/sphere-sunrise-design/input/templates/mix-match.json
{
    "header" : { "$ref" : "common/header.json" },
    "footer" : { "$ref" : "common/footer.json" },
    "content" : {
        "breadcrumb" : { "$ref" : "catalog/breadcrumb.json" },
        "gallery" : { "$ref" : "catalog/product-gallery.json" }
    },
    "meta" : { "$ref" : "common/meta.json" }
}

=== adnasa/sphere-sunrise-design/input/templates/checkout-shipping.json
{
    "header" : { "$ref" : "common/checkout-header.json" },
    "footer" : { "$ref" : "common/checkout-footer.json" },
    "content" : {
        "stepWidget" : {
            "shippingStepActive": true
        },
        "chooseTitle" : { "$ref" : "checkout/choose-title.json" },
        "chooseCountry" : { "$ref" : "checkout/choose-country.json" },
        "diffChooseCountry" :  { "$ref" : "checkout/choose-country.json" },
        "delivery" : { "$ref" : "checkout/shipping-methods.json" },
        "itemsTotal" : 3,
        "checkoutItem" : {
            "list" : [
                { "$ref" : "common/product-variant-1.json" },
                { "$ref" : "common/product-variant-1.json" },
                { "$ref" : "common/product-variant-1.json" }
            ]
        },
        "promoCode" : "Sunny Sale",
        "subtotal" : "107,00 €",
        "discount" : "0,00 €",
        "deliveryTitle" : "Standard Delivery",
        "deliverySum" : "10,00 €",
        "tax" : "20,00 €",
        "total" : "123,00 €"
    },
    "meta" : {
        "assetsPath": "assets/"
    }
}

=== adnasa/sphere-sunrise-design/input/templates/my-account-my-orders.json
{
	"header" : { "$ref" : "common/header.json" },
	"footer" : { "$ref" : "common/footer.json" },
	"content" : {
        "contentTitle" : "My Orders",
		"orderNumberTitle" : "Order Number",
		"dateTitle" : "Date",
		"paymentStatusTitle" : "Payment Status",
		"shippingTitle" : "Shipping",
		"order" : [
			{
				"orderNumber" : "1234567889952",
				"date" : "08.05.15",
				"total" : "100.00 €",
				"paymentStatus" : "Paid",
				"shipping" : "Delivered",
				"view" : "View"
			},
			{
				"orderNumber" : "1234567889952",
				"date" : "08.05.15",
				"total" : "100.00 €",
				"paymentStatus" : "Paid",
				"shipping" : "Delivered",
				"view" : "View"
			},
			{
				"orderNumber" : "1234567889952",
				"date" : "08.05.15",
				"total" : "100.00 €",
				"paymentStatus" : "Paid",
				"shipping" : "Delivered",
				"view" : "View"
			},
			{
				"orderNumber" : "1234567889952",
				"date" : "08.05.15",
				"total" : "100.00 €",
				"paymentStatus" : "Paid",
				"shipping" : "Delivered",
				"view" : "View"
			},
			{
				"orderNumber" : "1234567889952",
				"date" : "08.05.15",
				"total" : "100.00 €",
				"paymentStatus" : "Paid",
				"shipping" : "Delivered",
				"view" : "View"
			}
		]
	},
    "meta" : { "$ref" : "common/meta.json" }
}

=== adnasa/sphere-sunrise-design/input/templates/home.json
{
	"header" : { "$ref" : "common/header.json" },
	"footer" : { "$ref" : "common/footer.json" },
	"content" : {
		"suggestions" : [
			{
				"id" : "1",
				"name" : "Enditatem Product Name Optional very long line two",
				"description" : "Subline",
				"sku" : "Sunrise #SUN123456",
				"price" : "€ 49,-",
				"priceOld" : "€ 79,99",
				"rating2" : true,
				"url" : "",
				"addToCartUrl" : "",
				"addToWishlistUrl" : "",
				"addReviewUrl" : "",
				"new" : true,
				"moreColors" : true,
				"gallery" : {
					"mainImage" : "assets/img/blue-jacket.jpg",
					"list" : [
						{
							"thumbImage" : "assets/img/blue-jacket.jpg",
							"bigImage" : "assets/img/blue-jacket.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-jacket.jpg",
							"bigImage" : "assets/img/blue-jacket.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-jacket.jpg",
							"bigImage" : "assets/img/blue-jacket.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-jacket.jpg",
							"bigImage" : "assets/img/blue-jacket.jpg"
						}
					]
				},
				"attributes" : [
					{
						"name" : "Color",
						"list" : [
							{
								"text" : "Red",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "Blue",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "Green",
								"value" : "",
								"selected" : false
							}
						]
					},
					{
						"name" : "Size",
						"list" : [
							{
								"text" : "S",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "M",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "L",
								"value" : "",
								"selected" : false
							}
						]
					}
				]
			},
			{
				"id" : "2",
				"name" : "Enditatem Product Name Optional very long line two",
				"description" : "Subline",
				"sku" : "Sunrise #SUN123456",
				"price" : "€ 49,-",
				"priceOld" : "€ 79,99",
				"rating2" : true,
				"url" : "",
				"addToCartUrl" : "",
				"addToWishlistUrl" : "",
				"addReviewUrl" : "",
				"new" : true,
				"moreColors" : true,
				"gallery" : {
					"mainImage" : "assets/img/blue-shirt.jpg",
					"list" : [
						{
							"thumbImage" : "assets/img/blue-shirt.jpg",
							"bigImage" : "assets/img/blue-shirt.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-shirt.jpg",
							"bigImage" : "assets/img/blue-shirt.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-shirt.jpg",
							"bigImage" : "assets/img/blue-shirt.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-shirt.jpg",
							"bigImage" : "assets/img/blue-shirt.jpg"
						}
					]
				},
				"attributes" : [
					{
						"name" : "Color",
						"list" : [
							{
								"text" : "Red",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "Blue",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "Green",
								"value" : "",
								"selected" : false
							}
						]
					},
					{
						"name" : "Size",
						"list" : [
							{
								"text" : "S",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "M",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "L",
								"value" : "",
								"selected" : false
							}
						]
					}
				]
			},
			{
				"id" : "3",
				"name" : "Enditatem Product Name Optional very long line two",
				"description" : "Subline",
				"sku" : "Sunrise #SUN123456",
				"price" : "€ 49,-",
				"priceOld" : "€ 79,99",
				"rating2" : true,
				"url" : "",
				"addToCartUrl" : "",
				"addToWishlistUrl" : "",
				"addReviewUrl" : "",
				"new" : true,
				"moreColors" : true,
				"gallery" : {
					"mainImage" : "assets/img/blue-jacket.jpg",
					"list" : [
						{
							"thumbImage" : "assets/img/blue-jacket.jpg",
							"bigImage" : "assets/img/blue-jacket.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-jacket.jpg",
							"bigImage" : "assets/img/blue-jacket.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-jacket.jpg",
							"bigImage" : "assets/img/blue-jacket.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-jacket.jpg",
							"bigImage" : "assets/img/blue-jacket.jpg"
						}
					]
				},
				"attributes" : [
					{
						"name" : "Color",
						"list" : [
							{
								"text" : "Red",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "Blue",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "Green",
								"value" : "",
								"selected" : false
							}
						]
					},
					{
						"name" : "Size",
						"list" : [
							{
								"text" : "S",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "M",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "L",
								"value" : "",
								"selected" : false
							}
						]
					}
				]
			},
			{
				"id" : "4",
				"name" : "Enditatem Product Name Optional very long line two",
				"description" : "Subline",
				"sku" : "Sunrise #SUN123456",
				"price" : "€ 49,-",
				"priceOld" : "€ 79,99",
				"rating2" : true,
				"url" : "",
				"addToCartUrl" : "",
				"addToWishlistUrl" : "",
				"addReviewUrl" : "",
				"new" : true,
				"moreColors" : true,
				"gallery" : {
					"mainImage" : "assets/img/blue-shirt.jpg",
					"list" : [
						{
							"thumbImage" : "assets/img/blue-shirt.jpg",
							"bigImage" : "assets/img/blue-shirt.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-shirt.jpg",
							"bigImage" : "assets/img/blue-shirt.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-shirt.jpg",
							"bigImage" : "assets/img/blue-shirt.jpg"
						},
						{
							"thumbImage" : "assets/img/blue-shirt.jpg",
							"bigImage" : "assets/img/blue-shirt.jpg"
						}
					]
				},
				"attributes" : [
					{
						"name" : "Color",
						"list" : [
							{
								"text" : "Red",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "Blue",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "Green",
								"value" : "",
								"selected" : false
							}
						]
					},
					{
						"name" : "Size",
						"list" : [
							{
								"text" : "S",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "M",
								"value" : "",
								"selected" : false
							},
							{
								"text" : "L",
								"value" : "",
								"selected" : false
							}
						]
					}
				]
			}
		],
		"wishlistWidged" : {
			"text" : "Your Wishlist",
			"number" : "45",
			"recentAddedTitle" : "My recently added items",
			"viewWishlist" : {
				"text" : "View your wishlist",
				"url" : ""
			},
			"list" : [
				{
					"image" : "assets/img/blue-shirt.jpg"
				},
				{
					"image" : "assets/img/blue-shirt.jpg"
				},
				{
					"image" : "assets/img/blue-shirt.jpg"
				}
			]
		}
	},
	"meta" : {
		"assetsPath": "assets/",
		"bagItems" : [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
	}
}

=== adnasa/sphere-sunrise-design/input/templates/checkout-confirmation.json
{
	"header" : { "$ref" : "common/checkout-header.json" },
	"footer" : { "$ref" : "common/checkout-footer.json" },
  "content" : {
      "cart" : { "$ref" : "checkout/cart.json" },
      "stepWidget" : {
          "confirmationStepActive": true
      },
      "shippingAddress" : { "$ref" : "checkout/shipping-address.json" },
      "billingAddress" : { "$ref" : "checkout/billing-address.json" },
		"shippingMethod" : {
			"text" : "Shipping Method",
			"description" : "DHL Standard - Delivery 3-5 Days"
		},
		"paymentDetails" : {
			"text" : "Payment Details",
			"type" : "Credit Card",
			"name" : "Bruce Wayne",
			"card" : "Visa",
			"number" : "**** **** **** **56",
			"date" : "09.18"
		},
    "cartItems" : {
      "description" : "Product Description",
      "price" : "Price",
      "totalPrice" : "Total Price",
      "list" : [
        {
          "nameHeadline" : "Enditatem Product Name",
          "nameSubline" : "Optional Line Two",
          "sku" : "Sunrise #SUN123456",
          "color" : "Navy Blue",
          "size" : "M",
          "available" : "Available",
          "edit" : "Edit",
          "delete" : "Delete",
          "quantity" : 2,
          "priceOld" : "100,00 €",
          "price" : "49,00 €",
          "totalPrice" : "49,00 €"
        },
        {
          "nameHeadline" : "Enditatem Product Name",
          "nameSubline" : "Optional Line Two",
          "sku" : "Sunrise #SUN123456",
          "color" : "Navy Blue",
          "size" : "M",
          "available" : "Available",
          "edit" : "Edit",
          "delete" : "Delete",
          "quantity" : 3,
          "price" : "49,00 €",
          "totalPrice" : "49,00 €"
        }
      ]
    },
		"rememberMe" : {
			"text" : "Save my details to create my personal account at SUNRISE",
			"value" : ""
		},
		"newsletter" : {
			"text" : "Please add me to the",
			"description" : "SUNRISE Newsletter",
			"value" : "",
			"url" : ""
		},
		"totalSum" : {
			"subtotal" : "107,00 €",
			"orderDiscountTitle" : "Order Discount",
			"orderDiscount" : "0,00 €",
			"deliveryOption" : "Standard Delivery",
			"delivery" : "0,00 €",
			"tax" : "20,00 €",
			"orderTotalTitle" : "Order Total",
			"orderTotal" : "117,00 €"
		},
		"completeOrderBtn" : {
			"text" : "Complete my order",
			"url" : ""
		},
		"termsConditions" : {
			"text" : "I agree to the",
			"linkText" : "Terms and Conditions",
			"url" : ""
		}
  },
  "meta" : {
	"assetsPath": "assets/"
  }
}

=== adnasa/sphere-sunrise-design/input/templates/store-finder.json
{
	"header" : { "$ref" : "common/header.json" },
	"footer" : { "$ref" : "common/footer.json" },
	"content" : {
        "regionSelector" : [
            {
                "label" : "Region 1",
                "value" : "Region1",
                "selected" : false
            },
            {
                "label" : "Region 2",
                "value" : "Region2",
                "selected" : false
            }
        ],
        "citySelector" : [
            {
                "label" : "City 1",
                "value" : "City1",
                "selected" : false
            },
            {
                "label" : "City 2",
                "value" : "City2",
                "selected" : false
            }
        ],
        "storeSelector" : [
            {
                "label" : "Store 1",
                "value" : "Store1",
                "selected" : false
            },
            {
                "label" : "Store 2",
                "value" : "Store2",
                "selected" : false
            }
        ]
	},
	"meta" : { "$ref" : "common/meta.json" }
}

=== adnasa/sphere-sunrise-design/input/templates/checkout-payment.json
{
    "header" : { "$ref" : "common/checkout-header.json" },
    "footer" : { "$ref" : "common/checkout-footer.json" },
    "content" : {
        "stepWidget" : {
            "paymentStepActive": true
        },
        "paymentOption" : {
            "list" : [
                {
                    "text" : "Credit Card",
                    "image" : "assets/img/payment-option-card.gif",
                    "value" : "credit-card",
                    "selected" : false
                },
                {
                    "text" : "PayPal",
                    "image" : "assets/img/payment-option-paypal.png",
                    "value" : "paypal",
                    "selected" : false
                },
                {
                    "text" : "Pre-payment",
                    "image" : "assets/img/blank-img.jpg",
                    "value" : "prepaid",
                    "selected" : true
                }
            ]
        },
        "expiryDate" : { "$ref" : "checkout/months.json" },
        "year" : {
            "list" : [
                {
                    "text" : "2050",
                    "value" : "",
                    "selected" : false
                },
                {
                    "text" : "2100",
                    "value" : "",
                    "selected" : false
                }
            ]
        },
        "securityCode" : "Security Code",
        "securityCodeTooltip" : "Additional information about the security code goes here...",
        "cart" : { "$ref" : "checkout/cart.json" }
    },
    "meta" : {
        "assetsPath": "assets/"
    }
}

=== adnasa/sphere-sunrise-design/input/templates/faq.json
{
	"header" : { "$ref" : "common/header.json" },
	"footer" : { "$ref" : "common/footer.json" },
	"content" : {
        "deliveryFaqs" : [
            {
                "index" : "1",
                "title" : "1. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "text" : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit."
            },
            {
                "index" : "2",
                "title" : "2. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "text" : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit."
            }
        ],
        "returnsFaqs" : [
            {
                "index" : "3",
                "title" : "1. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "text" : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit."
            },
            {
                "index" : "4",
                "title" : "2. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "text" : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit."
            }
        ]
	},
	"meta" : { "$ref" : "common/meta.json" }
}
